/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Product;
import Business.ProductCatalog;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class VendorProductMgtJPanel extends javax.swing.JPanel {

    /**
     * Creates new form VendorProductMgtJPanel
     */

    private JPanel userProcessContainer;
    private ProductCatalog productCatalog;
    private String vendorSent;
    VendorProductMgtJPanel(JPanel userProcessContainer, ProductCatalog productCatalog, String vendorSent) {
       initComponents();
       this.userProcessContainer = userProcessContainer;
       this.productCatalog = productCatalog;
       this.vendorSent = vendorSent;
       populateTable();
    }
    
    public void populateTable()
    {
        DefaultTableModel defaultTable = (DefaultTableModel)vendorSpecificProductTable.getModel();
        defaultTable.setRowCount(0);
        
        
        if(vendorSent.equalsIgnoreCase("Dell"))
        {
        for(Product product : productCatalog.getProductCatalog()){
            
            if(product.getVendorName().equalsIgnoreCase("Dell")){
                
                Object row[] = new Object[4];
                row[0] = product;
                row[1] = product.getProductType();
                row[2] = product.getProductID();
                row[3] = product.getBasePrice();
                
                defaultTable.addRow(row);
            }
           }  
        }
        
        if(vendorSent.equalsIgnoreCase("HP"))
        {
        for(Product product : productCatalog.getProductCatalog()){
            
            if(product.getVendorName().equalsIgnoreCase("HP")){
                
                Object row[] = new Object[4];
                row[0] = product;
                row[1] = product.getProductType();
                row[2] = product.getProductID();
                row[3] = product.getBasePrice();
                
                defaultTable.addRow(row);
            }
           }  
        }
        
        if(vendorSent.equalsIgnoreCase("Canon"))
        {
        for(Product product : productCatalog.getProductCatalog()){
            
            if(product.getVendorName().equalsIgnoreCase("Canon")){
                
                Object row[] = new Object[4];
                row[0] = product;
                row[1] = product.getProductType();
                row[2] = product.getProductID();
                row[3] = product.getBasePrice();
                
                defaultTable.addRow(row);
            }
           }  
        }
        if(vendorSent.equalsIgnoreCase("Apple"))
        {
        for(Product product : productCatalog.getProductCatalog()){
            
            if(product.getVendorName().equalsIgnoreCase("Apple")){
                
                Object row[] = new Object[4];
                row[0] = product;
                row[1] = product.getProductType();
                row[2] = product.getProductID();
                row[3] = product.getBasePrice();
                
                defaultTable.addRow(row);
            }
           }  
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        vendorSpecificProductTable = new javax.swing.JTable();
        vendorCreateItemBtn = new javax.swing.JButton();
        viewSelectedItemBtn = new javax.swing.JButton();
        deleteProductBtn = new javax.swing.JButton();
        backVendorList = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 153, 153));

        vendorSpecificProductTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vendor Name", "Product Type", "Product ID", "Base Price"
            }
        ));
        jScrollPane2.setViewportView(vendorSpecificProductTable);

        jScrollPane1.setViewportView(jScrollPane2);

        vendorCreateItemBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        vendorCreateItemBtn.setText("Create New Item");
        vendorCreateItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendorCreateItemBtnActionPerformed(evt);
            }
        });

        viewSelectedItemBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        viewSelectedItemBtn.setText("View Selected Item");
        viewSelectedItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSelectedItemBtnActionPerformed(evt);
            }
        });

        deleteProductBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        deleteProductBtn.setText("Delete Selected Item");
        deleteProductBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteProductBtnActionPerformed(evt);
            }
        });

        backVendorList.setText("<< Back");
        backVendorList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backVendorListActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Your Products Under Business:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Vendor Management ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(backVendorList, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(deleteProductBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(viewSelectedItemBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vendorCreateItemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(216, 216, 216)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(392, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vendorCreateItemBtn)
                    .addComponent(viewSelectedItemBtn))
                .addGap(28, 28, 28)
                .addComponent(deleteProductBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(backVendorList)
                .addGap(120, 120, 120))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backVendorListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backVendorListActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backVendorListActionPerformed

    private void vendorCreateItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendorCreateItemBtnActionPerformed
        VendorCreateProductJPanel createPanel = new VendorCreateProductJPanel(userProcessContainer,productCatalog,vendorSent);
        userProcessContainer.add("VendorCreateProductJPanel",createPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_vendorCreateItemBtnActionPerformed

    private void viewSelectedItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSelectedItemBtnActionPerformed
        int selectedRow = vendorSpecificProductTable.getSelectedRow();
        if(selectedRow<0){
            
            JOptionPane.showMessageDialog(null, "Please Select a Row" , "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
        else{
            Product product = (Product)vendorSpecificProductTable.getValueAt(selectedRow, 0);
            VendorViewProductJPanel viewPanel = new VendorViewProductJPanel(userProcessContainer,product,vendorSent);
            userProcessContainer.add("VendorViewProductJPanel", viewPanel);
            CardLayout layout = (CardLayout)userProcessContainer.getLayout();
            layout.next(userProcessContainer);
            
        }
    }//GEN-LAST:event_viewSelectedItemBtnActionPerformed

    private void deleteProductBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProductBtnActionPerformed
        int selectedRow = vendorSpecificProductTable.getSelectedRow();
        if(selectedRow>=0){
            
            int dialogButton = JOptionPane.YES_NO_OPTION;
            getToolkit().beep();
            int dialogResult = JOptionPane.showConfirmDialog(null, "Are you Sure?","Warning",dialogButton);
            if (dialogResult == JOptionPane.YES_OPTION){
                
                Product product = (Product)vendorSpecificProductTable.getValueAt(selectedRow, 0);
                productCatalog.deleteProduct(product);
                populateTable();
                
            }
        }
        
        else{
            JOptionPane.showMessageDialog(null, "Please select a Row");
        }
    }//GEN-LAST:event_deleteProductBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backVendorList;
    private javax.swing.JButton deleteProductBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton vendorCreateItemBtn;
    private javax.swing.JTable vendorSpecificProductTable;
    private javax.swing.JButton viewSelectedItemBtn;
    // End of variables declaration//GEN-END:variables
}
