/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Product;
import Business.ProductCatalog;
import com.sun.glass.events.KeyEvent;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Lenovo
 */
public class VendorViewProductJPanel extends javax.swing.JPanel {

    /**
     * Creates new form VendorViewProductJPanel
     */
    
    private JPanel userProcessContainer;
    private Product product;
    private String vendorSent;

    VendorViewProductJPanel(JPanel userProcessContainer, Product product, String vendorSent) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.product = product;
        this.vendorSent = vendorSent;
        
        populateProductDetails();
        updateViewProdBtn.setEnabled(true);
        saveUpdatedProdBtn.setEnabled(false);
    }
    
    public void populateProductDetails(){
        
        vendorNameTextField.setText(product.getVendorName());
        productNameTextField.setText(product.getProductName());
        productTypeTextField.setText(product.getProductType());
        productIDTextField.setText(String.valueOf(product.getProductID()));
        productDescTextArea.setText(product.getProductDescription());
        productBenefitsTextArea.setText(product.getProductBenefits());
        floorPriceTextField.setText(String.valueOf(product.getFloorPrice()));
        ceilingPriceTextField.setText(String.valueOf(product.getCeilingPrice()));
        basePriceTextField.setText(String.valueOf(product.getBasePrice()));
        
        
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        vendorNameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        productTypeTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        productNameTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        productIDTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productDescTextArea = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        basePriceTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        floorPriceTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ceilingPriceTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        productBenefitsTextArea = new javax.swing.JTextArea();
        saveUpdatedProdBtn = new javax.swing.JButton();
        updateViewProdBtn = new javax.swing.JButton();
        backFromViewBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Vendor Name:");

        vendorNameTextField.setEditable(false);
        vendorNameTextField.setBackground(new java.awt.Color(153, 153, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Product type:");

        productTypeTextField.setEditable(false);
        productTypeTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                productTypeTextFieldFocusLost(evt);
            }
        });
        productTypeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productTypeTextFieldActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Product Name:");

        productNameTextField.setEditable(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Product ID:");

        productIDTextField.setEditable(false);
        productIDTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                productIDTextFieldKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Product Description:");

        productDescTextArea.setEditable(false);
        productDescTextArea.setColumns(20);
        productDescTextArea.setRows(5);
        jScrollPane1.setViewportView(productDescTextArea);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Base Price:");

        basePriceTextField.setEditable(false);
        basePriceTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                basePriceTextFieldKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Floor Price:");

        floorPriceTextField.setEditable(false);
        floorPriceTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                floorPriceTextFieldKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Ceiling Price:");

        ceilingPriceTextField.setEditable(false);
        ceilingPriceTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ceilingPriceTextFieldKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Product benefits:");

        productBenefitsTextArea.setEditable(false);
        productBenefitsTextArea.setColumns(20);
        productBenefitsTextArea.setRows(5);
        jScrollPane2.setViewportView(productBenefitsTextArea);

        saveUpdatedProdBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        saveUpdatedProdBtn.setText("Save");
        saveUpdatedProdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveUpdatedProdBtnActionPerformed(evt);
            }
        });

        updateViewProdBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        updateViewProdBtn.setText("Update");
        updateViewProdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateViewProdBtnActionPerformed(evt);
            }
        });

        backFromViewBtn.setText("<<Back");
        backFromViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backFromViewBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Selected Product Details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(saveUpdatedProdBtn)
                        .addGap(34, 34, 34)
                        .addComponent(updateViewProdBtn))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(69, 69, 69)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(39, 39, 39)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(vendorNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(productNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel6))
                            .addGap(68, 68, 68)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(productTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(productIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(69, 69, 69)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel4))
                                    .addGap(36, 36, 36))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel7)
                                    .addGap(28, 28, 28)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2)
                                .addComponent(jScrollPane1)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(basePriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                    .addComponent(ceilingPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(41, 41, 41)
                                    .addComponent(jLabel9)
                                    .addGap(44, 44, 44)
                                    .addComponent(floorPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(344, 344, 344)
                        .addComponent(backFromViewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel3)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(vendorNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(productTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(productNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(basePriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(floorPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(ceilingPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveUpdatedProdBtn)
                    .addComponent(updateViewProdBtn))
                .addGap(51, 51, 51)
                .addComponent(backFromViewBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void productTypeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productTypeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productTypeTextFieldActionPerformed

    private void updateViewProdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateViewProdBtnActionPerformed
        updateViewProdBtn.setEnabled(false);
        saveUpdatedProdBtn.setEnabled(true);
        vendorNameTextField.setText(vendorSent);
        
        productNameTextField.requestFocus();
        
        productNameTextField.setEditable(true);
        productTypeTextField.setEditable(true);
        productIDTextField.setEditable(true);
        productDescTextArea.setEditable(true);
        productBenefitsTextArea.setEditable(true);
        floorPriceTextField.setEditable(true);
        ceilingPriceTextField.setEditable(true);
        basePriceTextField.setEditable(true);
        
    }//GEN-LAST:event_updateViewProdBtnActionPerformed

    private void saveUpdatedProdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveUpdatedProdBtnActionPerformed
       
        if(productNameTextField.getText().equals("") || productDescTextArea.getText().equals("")||productBenefitsTextArea.getText().equals(""))
        {
           
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Make Sure All Values are Entered Correctly","Warning",JOptionPane.WARNING_MESSAGE);
        }
   else{
        
        
        try{
        product.setVendorName(vendorNameTextField.getText());
        product.setProductName(productNameTextField.getText());
        product.setProductID(Integer.parseInt(productIDTextField.getText()));
        product.setProductType(productTypeTextField.getText());
        product.setProductDescription(productDescTextArea.getText());
        product.setProductBenefits(productBenefitsTextArea.getText());
        product.setFloorPrice(Float.parseFloat(floorPriceTextField.getText()));
        product.setCeilingPrice(Float.parseFloat(ceilingPriceTextField.getText()));
        product.setBasePrice(Float.parseFloat(basePriceTextField.getText()));
        
        JOptionPane.showMessageDialog(null, "Updates are saved");
        updateViewProdBtn.setEnabled(true);
        saveUpdatedProdBtn.setEnabled(false);
        saveUpdatedProdBtn.setEnabled(false);
        productNameTextField.setEditable(false);
        productTypeTextField.setEditable(false);
        productIDTextField.setEditable(false);
        productDescTextArea.setEditable(false);
        productBenefitsTextArea.setEditable(false);
        floorPriceTextField.setEditable(false);
        ceilingPriceTextField.setEditable(false);
        basePriceTextField.setEditable(false);
        }
        catch(Exception e){
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Make Sure Entries Are Correct", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
      }  
        
    }//GEN-LAST:event_saveUpdatedProdBtnActionPerformed

    private void backFromViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backFromViewBtnActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length-1];
        VendorProductMgtJPanel managePanel = (VendorProductMgtJPanel)component;
        managePanel.populateTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backFromViewBtnActionPerformed

    private void productIDTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productIDTextFieldKeyTyped
        char pressedKey = evt.getKeyChar();
        if(!(Character.isDigit(pressedKey) || pressedKey == KeyEvent.VK_BACKSPACE || pressedKey == KeyEvent.VK_DELETE))
        {
            getToolkit().beep();
            
            JOptionPane.showMessageDialog(null, "Please Enter Numbers Only");
            evt.consume();
            
        }
    }//GEN-LAST:event_productIDTextFieldKeyTyped

    private void basePriceTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_basePriceTextFieldKeyTyped
        char pressedKey = evt.getKeyChar();
        if(!(Character.isDigit(pressedKey) || pressedKey == KeyEvent.VK_BACKSPACE || pressedKey == KeyEvent.VK_DELETE || pressedKey == KeyEvent.VK_PERIOD))
        {
            getToolkit().beep();
            
            JOptionPane.showMessageDialog(null, "Please Enter Valid Figures");
            evt.consume();
            
        }
    }//GEN-LAST:event_basePriceTextFieldKeyTyped

    private void ceilingPriceTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ceilingPriceTextFieldKeyTyped
        char pressedKey = evt.getKeyChar();
        if(!(Character.isDigit(pressedKey) || pressedKey == KeyEvent.VK_BACKSPACE || pressedKey == KeyEvent.VK_DELETE || pressedKey == KeyEvent.VK_PERIOD))
        {
            getToolkit().beep();
            
            JOptionPane.showMessageDialog(null, "Please Enter Valid Figures");
            evt.consume();
            
        }
    }//GEN-LAST:event_ceilingPriceTextFieldKeyTyped

    private void floorPriceTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_floorPriceTextFieldKeyTyped
        char pressedKey = evt.getKeyChar();
        if(!(Character.isDigit(pressedKey) || pressedKey == KeyEvent.VK_BACKSPACE || pressedKey == KeyEvent.VK_DELETE || pressedKey == KeyEvent.VK_PERIOD))
        {
            getToolkit().beep();
            
            JOptionPane.showMessageDialog(null, "Please Enter Valid Figures");
            evt.consume();
            
        }
    }//GEN-LAST:event_floorPriceTextFieldKeyTyped

    private void productTypeTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_productTypeTextFieldFocusLost
        String editedProductType = productTypeTextField.getText();
        if(!(editedProductType.equals("Computer") || editedProductType.equals("Printer") || editedProductType.equals("HardwareParts") || editedProductType.equals("SoftwareProducts"))){
           //JOptionPane.showMessageDialog(null, "Available Types : Computer/Printer/HardwareParts/SoftwareProducts");
           //productTypeTextField.requestFocus();
           
           String[] list = {"Computer","Printer","HardwareParts","SoftwareProducts"};
           JComboBox prodTypeBox = new JComboBox(list);
           prodTypeBox.setEditable(true);
           JOptionPane.showMessageDialog(null, prodTypeBox,"Invalid Entry. Please select any one",JOptionPane.QUESTION_MESSAGE);
           productTypeTextField.setText(prodTypeBox.getSelectedItem().toString());
        }
    }//GEN-LAST:event_productTypeTextFieldFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backFromViewBtn;
    private javax.swing.JTextField basePriceTextField;
    private javax.swing.JTextField ceilingPriceTextField;
    private javax.swing.JTextField floorPriceTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea productBenefitsTextArea;
    private javax.swing.JTextArea productDescTextArea;
    private javax.swing.JTextField productIDTextField;
    private javax.swing.JTextField productNameTextField;
    private javax.swing.JTextField productTypeTextField;
    private javax.swing.JButton saveUpdatedProdBtn;
    private javax.swing.JButton updateViewProdBtn;
    private javax.swing.JTextField vendorNameTextField;
    // End of variables declaration//GEN-END:variables
}
