/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.ProductCatalog;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Lenovo
 */
public class VendorListJPanel extends javax.swing.JPanel {

    /**
     * Creates new form VendorDetailsJPanel
     */
   
    protected String vendorSent = "";
    private JPanel userProcessContainer;
    private ProductCatalog productCatalog;
    
    VendorListJPanel(JPanel userProcessContainer, ProductCatalog productCatalog) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.productCatalog = productCatalog;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dellBtn = new javax.swing.JButton();
        hpBtn = new javax.swing.JButton();
        canonBtn = new javax.swing.JButton();
        appleBtn = new javax.swing.JButton();
        backFromVendorListBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 153, 153));

        dellBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dellBtn.setText("Dell");
        dellBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dellBtnActionPerformed(evt);
            }
        });

        hpBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hpBtn.setText("HP");
        hpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hpBtnActionPerformed(evt);
            }
        });

        canonBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        canonBtn.setText("Canon");
        canonBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canonBtnActionPerformed(evt);
            }
        });

        appleBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        appleBtn.setText("Apple");
        appleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appleBtnActionPerformed(evt);
            }
        });

        backFromVendorListBtn.setText("<<Back");
        backFromVendorListBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backFromVendorListBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Please Choose the Brand You Represent");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dellBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(canonBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(appleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 162, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(backFromVendorListBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dellBtn)
                    .addComponent(hpBtn))
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(canonBtn)
                    .addComponent(appleBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(backFromVendorListBtn)
                .addGap(142, 142, 142))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void canonBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canonBtnActionPerformed
        vendorSent = "Canon";
        VendorProductMgtJPanel vendorProdMgt = new VendorProductMgtJPanel(userProcessContainer,productCatalog, vendorSent);
        userProcessContainer.add("VendorProductMgtJPanel", vendorProdMgt);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_canonBtnActionPerformed

    private void backFromVendorListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backFromVendorListBtnActionPerformed
        // TODO add your handling code here:
        
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backFromVendorListBtnActionPerformed

    private void dellBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dellBtnActionPerformed
        vendorSent = "Dell";
        VendorProductMgtJPanel vendorProdMgt = new VendorProductMgtJPanel(userProcessContainer,productCatalog, vendorSent);
        userProcessContainer.add("VendorProductMgtJPanel", vendorProdMgt);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_dellBtnActionPerformed

    private void hpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hpBtnActionPerformed
        vendorSent = "HP";
        VendorProductMgtJPanel vendorProdMgt = new VendorProductMgtJPanel(userProcessContainer,productCatalog, vendorSent);
        userProcessContainer.add("VendorProductMgtJPanel", vendorProdMgt);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_hpBtnActionPerformed

    private void appleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appleBtnActionPerformed
        vendorSent = "Apple";
        VendorProductMgtJPanel vendorProdMgt = new VendorProductMgtJPanel(userProcessContainer,productCatalog, vendorSent);
        userProcessContainer.add("VendorProductMgtJPanel", vendorProdMgt);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_appleBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton appleBtn;
    private javax.swing.JButton backFromVendorListBtn;
    private javax.swing.JButton canonBtn;
    private javax.swing.JButton dellBtn;
    private javax.swing.JButton hpBtn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
