/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ResearchRole;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.ResearchOrganization;
import Business.ResearchParameters.Crop;
import Business.ResearchParameters.CropDirectory;
import Business.ResearchParameters.SoilParameter;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CropTestResultQueue;
import UserInterface.SignUpJPanel;
import UserInterface.SystemAdminRole.ManageNetworkJPanel;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Lenovo
 */
public class SendResultJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SendResultJPanel
     */
    
    private JPanel userProcessContainer;
    private CropTestResultQueue request;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private Image image2;
    
    public SendResultJPanel(JPanel userProcessContainer, CropTestResultQueue request, UserAccount userAccount, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        cropTxtFld.setText(request.getPlannedCropType());
        backgroundImage("/resources/imgs/HP2.jpg");
        populateActualValues();
    }
    
    private void backgroundImage(String str){
        try {
            BufferedImage image1 = ImageIO.read(ManageNetworkJPanel.class.getResource(str));
            image2 = image1.getScaledInstance(1200,800,Image.SCALE_SMOOTH);
        } catch (IOException ex) {
            Logger.getLogger(SignUpJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    
    public void paintComponent(Graphics g) {
    super.paintComponent(g);

    // Draw the background image.
    g.drawImage(image2, 0, 0, this);
  }
    
    public void populateActualValues()
    {
     actualBlkTxtFld.setText(String.valueOf(request.getActualBulkDensity()));
     actualElectricalTxtFld.setText(String.valueOf(request.getActualElectricalConductivity()));
     actualNitrateTxtFld.setText(String.valueOf(request.getActualNitrateLevel()));
     actualPhTxtFld.setText(String.valueOf(request.getActualSoilPH()));
     actualWaterTxtFld.setText(String.valueOf(request.getActualWaterContent()));
     actualOrganicCarbonTextField.setText(String.valueOf(request.getActualOrganicCarbon()));
     actualCNRatioTextField.setText(String.valueOf(request.getActualCarbonNitrogenRatio()));
     actualAluminiumSaturationTextField.setText(String.valueOf(request.getActualAluminiumSaturation()));
     actualCalciumCarbonateContentTextField.setText(String.valueOf(request.getActualCalciumCarbonateContent()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        researchResultTextField = new javax.swing.JTextField();
        backToResearchWorkAreaBtn = new javax.swing.JButton();
        submitResearchStudyBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cropTxtFld = new javax.swing.JTextField();
        actualBlkTxtFld = new javax.swing.JTextField();
        actualPhTxtFld = new javax.swing.JTextField();
        actualNitrateTxtFld = new javax.swing.JTextField();
        actualWaterTxtFld = new javax.swing.JTextField();
        actualElectricalTxtFld = new javax.swing.JTextField();
        expectedBlkTxtFld = new javax.swing.JTextField();
        expectedPhTxtFld = new javax.swing.JTextField();
        expectedNitrateTxtFld = new javax.swing.JTextField();
        expectedElectricalTxtFld = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        conductResearchJButton = new javax.swing.JButton();
        searchForThisCropJButton = new javax.swing.JButton();
        actualOrganicCarbonTextField = new javax.swing.JTextField();
        actualAluminiumSaturationTextField = new javax.swing.JTextField();
        actualCalciumCarbonateContentTextField = new javax.swing.JTextField();
        actualCNRatioTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        expectedOrganicCarbonTextField = new javax.swing.JTextField();
        expectedAluminiumSaturationTextField = new javax.swing.JTextField();
        expectedCalciumCarbonateContentTextField = new javax.swing.JTextField();
        expectedCNRatioTextField = new javax.swing.JTextField();
        expectedWaterContentTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Result:");

        researchResultTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                researchResultTextFieldActionPerformed(evt);
            }
        });

        backToResearchWorkAreaBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backToResearchWorkAreaBtn.setText("<<Back");
        backToResearchWorkAreaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToResearchWorkAreaBtnActionPerformed(evt);
            }
        });

        submitResearchStudyBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        submitResearchStudyBtn.setText("Submit Research Result");
        submitResearchStudyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitResearchStudyBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Bulk Density(g/cc):");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("pH:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Nitrate Level(ppm):");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Water Content:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Electrical Conductivity:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("For Crop: ");

        cropTxtFld.setEditable(false);

        actualBlkTxtFld.setEnabled(false);

        actualPhTxtFld.setEnabled(false);

        actualNitrateTxtFld.setEnabled(false);

        actualWaterTxtFld.setEnabled(false);

        actualElectricalTxtFld.setEnabled(false);

        expectedPhTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expectedPhTxtFldActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Expected:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Actual:");

        conductResearchJButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        conductResearchJButton.setText("Conduct Research");
        conductResearchJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conductResearchJButtonActionPerformed(evt);
            }
        });

        searchForThisCropJButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        searchForThisCropJButton.setText("Search For this Crop");
        searchForThisCropJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchForThisCropJButtonActionPerformed(evt);
            }
        });

        actualOrganicCarbonTextField.setEnabled(false);

        actualAluminiumSaturationTextField.setEnabled(false);

        actualCalciumCarbonateContentTextField.setEnabled(false);

        actualCNRatioTextField.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Organic Carbon(%):");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("C/N Ratio:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Aluminium Saturation(ppm):");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("CalciumCarbonate:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Process Research Result");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16)
                                .addGap(94, 94, 94))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(actualBlkTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(actualElectricalTxtFld, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(actualWaterTxtFld, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(actualNitrateTxtFld, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(actualPhTxtFld, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(actualOrganicCarbonTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(actualCNRatioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(actualAluminiumSaturationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(actualCalciumCarbonateContentTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(70, 70, 70)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(expectedPhTxtFld)
                            .addComponent(expectedNitrateTxtFld)
                            .addComponent(expectedElectricalTxtFld)
                            .addComponent(expectedAluminiumSaturationTextField)
                            .addComponent(expectedCNRatioTextField)
                            .addComponent(expectedOrganicCarbonTextField)
                            .addComponent(expectedCalciumCarbonateContentTextField)
                            .addComponent(expectedBlkTxtFld)
                            .addComponent(expectedWaterContentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel14))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(submitResearchStudyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(researchResultTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backToResearchWorkAreaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(cropTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(searchForThisCropJButton)
                                .addGap(36, 36, 36)
                                .addComponent(conductResearchJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel7)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cropTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchForThisCropJButton)
                    .addComponent(conductResearchJButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actualBlkTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(expectedBlkTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actualPhTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(expectedPhTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actualNitrateTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(expectedNitrateTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actualWaterTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(expectedWaterContentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actualElectricalTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(expectedElectricalTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(actualOrganicCarbonTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(actualCNRatioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel10)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(actualAluminiumSaturationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(actualCalciumCarbonateContentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(expectedOrganicCarbonTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(expectedCNRatioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(expectedAluminiumSaturationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(expectedCalciumCarbonateContentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(researchResultTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitResearchStudyBtn)
                    .addComponent(backToResearchWorkAreaBtn))
                .addGap(42, 42, 42))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backToResearchWorkAreaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToResearchWorkAreaBtnActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ResearchWorkAreaJPanel rwajp = (ResearchWorkAreaJPanel) component;
        rwajp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backToResearchWorkAreaBtnActionPerformed

    private void submitResearchStudyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitResearchStudyBtnActionPerformed
       
        try
        {
            String message = researchResultTextField.getText();
            request.setResolveDate(new Date());
            request.setMessage(message);
            //request.setSender(userAccount);
            request.setStatus("Research Done");
            request.setTestResult("Completed");
            //
            request.getCrop().setCropName(cropTxtFld.getText());
            request.getCrop().getSoilParameter().setExpectedBulkDensity(Float.parseFloat(expectedBlkTxtFld.getText()));
            request.getCrop().getSoilParameter().setExpectedNitrateLevel(Float.parseFloat(expectedNitrateTxtFld.getText()));
            request.getCrop().getSoilParameter().setExpectedElectricalConductivity(Float.parseFloat(expectedElectricalTxtFld.getText()));
            request.getCrop().getSoilParameter().setExpectedSoilPH(Float.parseFloat(expectedPhTxtFld.getText()));

            //---------------

            request.getCrop().getSoilParameter().setExpectedOrganicCarbon(Float.parseFloat(expectedOrganicCarbonTextField.getText()));
            request.getCrop().getSoilParameter().setExpectedCarbonNitrogenRatio(Float.parseFloat(expectedCNRatioTextField.getText()));
            request.getCrop().getSoilParameter().setExpectedAluminiumSaturation(Float.parseFloat(expectedAluminiumSaturationTextField.getText()));
            request.getCrop().getSoilParameter().setExpectedCalciumCarbonateContent(Float.parseFloat(expectedCalciumCarbonateContentTextField.getText()));
            request.getCrop().getSoilParameter().setExpectedWaterContent(Float.parseFloat(expectedWaterContentTextField.getText()));

            //Setting Remarks

            request.getCrop().getSoilParameter().businessLogicWaterContent(Float.parseFloat(actualWaterTxtFld.getText()));        
            request.getCrop().getSoilParameter().businessLogicSoilPH(Float.parseFloat(actualPhTxtFld.getText()));
            request.getCrop().getSoilParameter().businessLogicAluminiumSaturation(Float.parseFloat(actualAluminiumSaturationTextField.getText()));
            request.getCrop().getSoilParameter().businessLogicBulkDensity(Float.parseFloat(actualBlkTxtFld.getText()));
            request.getCrop().getSoilParameter().businessLogicCalciumCarbonateContent(Float.parseFloat(actualCalciumCarbonateContentTextField.getText()));
            request.getCrop().getSoilParameter().businessLogicCarbonNitrogenRatio(Float.parseFloat(actualCNRatioTextField.getText()));
            request.getCrop().getSoilParameter().businessLogicElectricalConductivity(Float.parseFloat(actualElectricalTxtFld.getText()));
            request.getCrop().getSoilParameter().businessLogicNitrateLevel(Float.parseFloat(actualNitrateTxtFld.getText()));
            request.getCrop().getSoilParameter().businessLogicOrganicCarbon(Float.parseFloat(actualOrganicCarbonTextField.getText()));
            
            //Clearing fields
            
            JOptionPane.showMessageDialog(null, "Research completed successfully");
            userProcessContainer.remove(this);
            Component[] componentArray = userProcessContainer.getComponents();
            Component component = componentArray[componentArray.length - 1];
            ResearchWorkAreaJPanel rwajp = (ResearchWorkAreaJPanel) component;
            rwajp.populateTable();
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.previous(userProcessContainer);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Please fill all the fields correctly");
        }
 
    }//GEN-LAST:event_submitResearchStudyBtnActionPerformed

    private void searchForThisCropJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchForThisCropJButtonActionPerformed
        // TODO add your handling code here:
        boolean received = false;
        for(Organization organization : enterprise.getOrganizationDirectory().getOrganizationList())
        {
            if(organization instanceof ResearchOrganization)
            {
                
                for(Crop crop :((ResearchOrganization) organization).getCropDirectory().getCropList())
                {
                    if(crop.getCropName().equalsIgnoreCase(cropTxtFld.getText()))
                    {
                        received = true;
//                        crop.getSoilParameter().businessLogic(request.getActualSoilPH());
                        
                        //Populating Expected values
                        
                        float electricalConductivity = crop.getSoilParameter().getExpectedElectricalConductivity();
                        expectedElectricalTxtFld.setText(String.valueOf(electricalConductivity));
                        
                        float bulkDensity = crop.getSoilParameter().getExpectedBulkDensity();
                        expectedBlkTxtFld.setText(String.valueOf(bulkDensity));
                        
                        float ph = crop.getSoilParameter().getExpectedSoilPH();
                        expectedPhTxtFld.setText(String.valueOf(ph));
                        
                        float nitrateLevel = crop.getSoilParameter().getExpectedNitrateLevel();
                        expectedNitrateTxtFld.setText(String.valueOf(nitrateLevel));
                        
                        float organicCarbon = crop.getSoilParameter().getExpectedOrganicCarbon();
                        expectedOrganicCarbonTextField.setText(String.valueOf(organicCarbon));
                        
                        float CN = crop.getSoilParameter().getExpectedCarbonNitrogenRatio();
                        expectedCNRatioTextField.setText(String.valueOf(CN));
                        
                        float alumunium = crop.getSoilParameter().getExpectedAluminiumSaturation();
                        expectedAluminiumSaturationTextField.setText(String.valueOf(alumunium));
                        
                        float calciumCarbonate = crop.getSoilParameter().getExpectedCalciumCarbonateContent();
                        expectedCalciumCarbonateContentTextField.setText(String.valueOf(calciumCarbonate));
                        
                        float waterContent = crop.getSoilParameter().getExpectedWaterContent();
                        expectedWaterContentTextField.setText(String.valueOf(waterContent));
                    }
                }
                if(received == false)
                    {
                        JOptionPane.showMessageDialog(null, "No Such Crop found.Please Conduct Research");
                    }
            }
            
            
            
        }
    }//GEN-LAST:event_searchForThisCropJButtonActionPerformed

    private void conductResearchJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conductResearchJButtonActionPerformed
        ConductResearchJPanel conductResearchJPanel = new ConductResearchJPanel(userProcessContainer, userAccount, enterprise);
        userProcessContainer.add("conductingResearchJPanel", conductResearchJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_conductResearchJButtonActionPerformed

    private void expectedPhTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expectedPhTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expectedPhTxtFldActionPerformed

    private void researchResultTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_researchResultTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_researchResultTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField actualAluminiumSaturationTextField;
    private javax.swing.JTextField actualBlkTxtFld;
    private javax.swing.JTextField actualCNRatioTextField;
    private javax.swing.JTextField actualCalciumCarbonateContentTextField;
    private javax.swing.JTextField actualElectricalTxtFld;
    private javax.swing.JTextField actualNitrateTxtFld;
    private javax.swing.JTextField actualOrganicCarbonTextField;
    private javax.swing.JTextField actualPhTxtFld;
    private javax.swing.JTextField actualWaterTxtFld;
    private javax.swing.JButton backToResearchWorkAreaBtn;
    private javax.swing.JButton conductResearchJButton;
    private javax.swing.JTextField cropTxtFld;
    private javax.swing.JTextField expectedAluminiumSaturationTextField;
    private javax.swing.JTextField expectedBlkTxtFld;
    private javax.swing.JTextField expectedCNRatioTextField;
    private javax.swing.JTextField expectedCalciumCarbonateContentTextField;
    private javax.swing.JTextField expectedElectricalTxtFld;
    private javax.swing.JTextField expectedNitrateTxtFld;
    private javax.swing.JTextField expectedOrganicCarbonTextField;
    private javax.swing.JTextField expectedPhTxtFld;
    private javax.swing.JTextField expectedWaterContentTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField researchResultTextField;
    private javax.swing.JButton searchForThisCropJButton;
    private javax.swing.JButton submitResearchStudyBtn;
    // End of variables declaration//GEN-END:variables
}
