/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.FarmerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.AdminOrganization;
import Business.Organization.CollectionCenterOrganization;
import Business.Organization.Organization;
import Business.WorkQueue.FarmerFeedbackWorkRequest;
import UserInterface.SignUpJPanel;
import UserInterface.SystemAdminRole.ManageNetworkJPanel;
import java.awt.CardLayout;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Lenovo
 */
public class FarmerFeedbackJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FarmerFeedbackJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private EcoSystem business;
    private Image image2;
    private String researchSatisfaction="";
    private String overallRating="";
    public FarmerFeedbackJPanel(JPanel userProcessContainer,Enterprise enterprise,EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.business = business;
        backgroundImage("/resources/imgs/HP2.jpg");
    }
    
    private void backgroundImage(String str){
        try {
            BufferedImage image1 = ImageIO.read(ManageNetworkJPanel.class.getResource(str));
            image2 = image1.getScaledInstance(1200,800,Image.SCALE_SMOOTH);
        } catch (IOException ex) {
            Logger.getLogger(SignUpJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    
    public void paintComponent(Graphics g) {
    super.paintComponent(g);

    // Draw the background image.
    g.drawImage(image2, 0, 0, this);
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        researchSatisfactionRadioGrp = new javax.swing.ButtonGroup();
        overallRateRadioGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        farmerNameTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        notSatisfiedRadio = new javax.swing.JRadioButton();
        satisfiedRadio = new javax.swing.JRadioButton();
        verySatifiedRadio = new javax.swing.JRadioButton();
        NARadio = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        overallBadRadio = new javax.swing.JRadioButton();
        overallGoodRadio = new javax.swing.JRadioButton();
        overallExcellentRadio = new javax.swing.JRadioButton();
        userFriendlyDropdown = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        remarksTextArea = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Your Feedback Is Important To Us");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Name:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("How  Userfriendly Is Our Website");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Are You Satisfied With The Research Solution Provided");

        researchSatisfactionRadioGrp.add(notSatisfiedRadio);
        notSatisfiedRadio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        notSatisfiedRadio.setText("Not Satisfied");
        notSatisfiedRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notSatisfiedRadioActionPerformed(evt);
            }
        });

        researchSatisfactionRadioGrp.add(satisfiedRadio);
        satisfiedRadio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        satisfiedRadio.setText("Somewhat Satisfied");
        satisfiedRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satisfiedRadioActionPerformed(evt);
            }
        });

        researchSatisfactionRadioGrp.add(verySatifiedRadio);
        verySatifiedRadio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        verySatifiedRadio.setText("Very Satisfied");
        verySatifiedRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verySatifiedRadioActionPerformed(evt);
            }
        });

        researchSatisfactionRadioGrp.add(NARadio);
        NARadio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        NARadio.setText("NA");
        NARadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NARadioActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Overall Rating");

        overallRateRadioGroup.add(overallBadRadio);
        overallBadRadio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        overallBadRadio.setText("Bad");
        overallBadRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overallBadRadioActionPerformed(evt);
            }
        });

        overallRateRadioGroup.add(overallGoodRadio);
        overallGoodRadio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        overallGoodRadio.setText("Good");
        overallGoodRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overallGoodRadioActionPerformed(evt);
            }
        });

        overallRateRadioGroup.add(overallExcellentRadio);
        overallExcellentRadio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        overallExcellentRadio.setText("Excellent");
        overallExcellentRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overallExcellentRadioActionPerformed(evt);
            }
        });

        userFriendlyDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select", "Easy To Use", "Somewhat Difficult", "Very Difficult" }));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Remarks");

        remarksTextArea.setColumns(20);
        remarksTextArea.setRows(5);
        jScrollPane1.setViewportView(remarksTextArea);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("<<Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imgs/agronomyAdvancement.JPG"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(166, 166, 166)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(144, 144, 144)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(notSatisfiedRadio)
                                    .addComponent(overallBadRadio))
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(satisfiedRadio)
                                    .addComponent(overallGoodRadio))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(overallExcellentRadio)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(verySatifiedRadio)
                                        .addGap(78, 78, 78)
                                        .addComponent(NARadio))))
                            .addComponent(farmerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userFriendlyDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 1327, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(327, 327, 327)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(farmerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel4)
                        .addGap(10, 10, 10)
                        .addComponent(userFriendlyDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel5)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(notSatisfiedRadio)
                            .addComponent(satisfiedRadio)
                            .addComponent(verySatifiedRadio)
                            .addComponent(NARadio))
                        .addGap(19, 19, 19)
                        .addComponent(jLabel6)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(overallBadRadio)
                            .addComponent(overallGoodRadio)
                            .addComponent(overallExcellentRadio))
                        .addGap(19, 19, 19)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))))
                .addContainerGap(73, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void notSatisfiedRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notSatisfiedRadioActionPerformed
        // TODO add your handling code here:
        researchSatisfaction = "Not Satisfied";
    }//GEN-LAST:event_notSatisfiedRadioActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String name = farmerNameTextField.getText();
        String remarks = remarksTextArea.getText();
        String userFriendliness = String.valueOf(userFriendlyDropdown.getSelectedItem());
        
        if(researchSatisfaction.equals("")|| overallRating.equals("")||userFriendliness.equals("Please Select")
                ||name.equals("")){
            JOptionPane.showMessageDialog(null, "Make Sure All Fields are Entered");
            return;
        }

        
        
        FarmerFeedbackWorkRequest request = new FarmerFeedbackWorkRequest();
        request.setFarmerName(name);
        request.setResearchSolutionHelped(researchSatisfaction);
        request.setSiteUserFriendly(userFriendliness);
        request.setOverallRating(overallRating);
        request.setRemarks(remarks);
        
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            
            if (organization instanceof AdminOrganization){
                org = organization;
                break;
            }
        }
        
        if (org!=null){
            org.getFeedbackWorkQueue().getFarmerFeedbackList().add(request);
            JOptionPane.showMessageDialog(null, "Feedback Submitted Successfully! We'll Work On It");
        }
        
        
        researchSatisfactionRadioGrp.clearSelection();
        overallRateRadioGroup.clearSelection();
        farmerNameTextField.setText("");
        remarksTextArea.setText("");
        userFriendlyDropdown.setSelectedIndex(0);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void satisfiedRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satisfiedRadioActionPerformed
        // TODO add your handling code here:
        researchSatisfaction = "Somewhat Satisfied";
    }//GEN-LAST:event_satisfiedRadioActionPerformed

    private void verySatifiedRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verySatifiedRadioActionPerformed
        // TODO add your handling code here:
        researchSatisfaction = "Very Satisfied";
    }//GEN-LAST:event_verySatifiedRadioActionPerformed

    private void NARadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NARadioActionPerformed
        // TODO add your handling code here:
        researchSatisfaction = "Not Applicable";
    }//GEN-LAST:event_NARadioActionPerformed

    private void overallBadRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overallBadRadioActionPerformed
         // TODO add your handling code here:
        overallRating = "Bad";
    }//GEN-LAST:event_overallBadRadioActionPerformed

    private void overallGoodRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overallGoodRadioActionPerformed
        // TODO add your handling code here:
        overallRating = "Good";
    }//GEN-LAST:event_overallGoodRadioActionPerformed

    private void overallExcellentRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overallExcellentRadioActionPerformed
        // TODO add your handling code here:
        overallRating = "Excellent";
    }//GEN-LAST:event_overallExcellentRadioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton NARadio;
    private javax.swing.JTextField farmerNameTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton notSatisfiedRadio;
    private javax.swing.JRadioButton overallBadRadio;
    private javax.swing.JRadioButton overallExcellentRadio;
    private javax.swing.JRadioButton overallGoodRadio;
    private javax.swing.ButtonGroup overallRateRadioGroup;
    private javax.swing.JTextArea remarksTextArea;
    private javax.swing.ButtonGroup researchSatisfactionRadioGrp;
    private javax.swing.JRadioButton satisfiedRadio;
    private javax.swing.JComboBox<String> userFriendlyDropdown;
    private javax.swing.JRadioButton verySatifiedRadio;
    // End of variables declaration//GEN-END:variables
}
