/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.FarmerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.MarketingOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.MarketWorkRequest;
import UserInterface.SignUpJPanel;
import UserInterface.SystemAdminRole.ManageNetworkJPanel;
import java.awt.CardLayout;
import java.awt.Graphics;
import java.awt.Image;
import static java.awt.Image.SCALE_SMOOTH;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kkgarg
 */
public class SellCropJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SellCropJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private ImageIcon imgFinal;
    private EcoSystem business;
    private Image image2;
    
    public SellCropJPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise, EcoSystem business) 
    {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.business = business;
        backgroundImage("/resources/imgs/HP2.jpg");
        farmerNamejTextField.setText(userAccount.getFarmer().getFarmerName());
        populateMarketSellTable();
        
    }
    
    private void backgroundImage(String str){
        try {
            BufferedImage image1 = ImageIO.read(ManageNetworkJPanel.class.getResource(str));
            image2 = image1.getScaledInstance(1200,800,Image.SCALE_SMOOTH);
        } catch (IOException ex) {
            Logger.getLogger(SignUpJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    
    public void paintComponent(Graphics g) {
    super.paintComponent(g);

    // Draw the background image.
    g.drawImage(image2, 0, 0, this);
  }

    public void populateMarketSellTable(){
        DefaultTableModel model = (DefaultTableModel) sellCropJTable.getModel();
        
        model.setRowCount(0);
        for (MarketWorkRequest request : userAccount.getMarketWorkQueue().getMarkerWorkRequestList()){
            Object[] row = new Object[5];
            row[0] = request;
            row[1] = request.getCropName();
            row[2] = request.getQuantity();
            row[3] = request.getRatePerKg();
  //          String status = request.getStatus();
            row[4] = request.getStatus() == null ? "Open" : request.getStatus();
            
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        sellCropJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        farmerNamejTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cropNameJTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        qtyTxtField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ratePerKgTxtF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        senderAddL1TextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        senderZipcodeJTextField = new javax.swing.JTextField();
        senderAddLine2TextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        postJButton = new javax.swing.JButton();
        viewJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        senderContactJTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        cropDescJTextArea = new javax.swing.JTextArea();
        uploadImageJButton = new javax.swing.JButton();
        cropImageJLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setEnabled(false);

        sellCropJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Farmer Name", "Crop Name", "Quantity", "Rate per Kg", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(sellCropJTable);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Sale Request Table");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Farmer's Name:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Crop Name:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Quantity:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Rate per Kg:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Line1:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Zip Code:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Line2:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Your Address");

        postJButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        postJButton.setText("Post Details");
        postJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postJButtonActionPerformed(evt);
            }
        });

        viewJButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        viewJButton.setText("View Vendor Response");
        viewJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewJButtonActionPerformed(evt);
            }
        });

        backJButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Contact No:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Write About your Crop:");

        cropDescJTextArea.setColumns(20);
        cropDescJTextArea.setRows(5);
        jScrollPane2.setViewportView(cropDescJTextArea);

        uploadImageJButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        uploadImageJButton.setText("Upload Crop Image");
        uploadImageJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadImageJButtonActionPerformed(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imgs/agronomyAdvancement.JPG"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 1327, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(174, 174, 174)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(97, 97, 97)
                                                .addComponent(qtyTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ratePerKgTxtF, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cropNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(farmerNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(100, 100, 100)))
                                    .addGap(28, 28, 28)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel8)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(senderAddLine2TextField, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(senderAddL1TextField, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(senderZipcodeJTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(senderContactJTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(69, 69, 69))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(114, 114, 114)))
                            .addGap(94, 94, 94)
                            .addComponent(cropImageJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(77, 77, 77)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(backJButton)
                                    .addGap(262, 262, 262)
                                    .addComponent(postJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(254, 254, 254)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(uploadImageJButton))
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(viewJButton))))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewJButton))
                .addGap(15, 15, 15)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(farmerNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(cropNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(qtyTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(ratePerKgTxtF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(senderAddL1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(senderAddLine2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(senderZipcodeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(senderContactJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(cropImageJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uploadImageJButton))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(postJButton)
                    .addComponent(backJButton))
                .addContainerGap(66, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
        
    }//GEN-LAST:event_backJButtonActionPerformed

    private void uploadImageJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadImageJButtonActionPerformed
        // TODO add your handling code here:
//        try{
//                
//       JFileChooser chooser=new JFileChooser();
//       chooser.showOpenDialog(null);
//       File f=chooser.getSelectedFile();
//       
//       Image image=ImageIO.read(f);
//       
//       String fileName=f.getAbsolutePath();
//       
//       if (fileName.endsWith(".jpg") || fileName.endsWith("jpeg"))
//       {
////       imagePathTextField.setText(fileName);
//           //Image picture1 = resume_image.getImage();
//         //Image picture2 = picture1.getScaledInstance(createPicture.getWidth(),createPicture.getHeight(),Image.SCALE_SMOOTH);
//         //Image picture2 = picture1.getScaledInstance(200,200,Image.SCALE_SMOOTH);
//         //ImageIcon picture3 = new ImageIcon(picture2.);
//        //ImageIcon picture2 = new ImageIcon(picture1);
//       ImageIcon icon=new ImageIcon(fileName);
//       cropImageJLabel.setIcon(new ImageIcon(image.getScaledInstance(154,127,150)));
//       cropImage = new ImageIcon(image.getScaledInstance(154,127,150));
//       }
//       
//       else
//       {
//            getToolkit().beep();
//            
//            JOptionPane.showMessageDialog(null, "Please select jpg or jpeg images only");
//            
//            
//       }
//       
//     }
//       
//       catch(Exception e){
//       }
        

        JFileChooser chooser=new JFileChooser();
       chooser.showOpenDialog(null);
       File image=chooser.getSelectedFile();
       String fName=image.getAbsolutePath();
       ImageIcon imgIcon=new ImageIcon(fName);        
       Image img=imgIcon.getImage();
       Image pic=img.getScaledInstance(cropImageJLabel.getWidth(), cropImageJLabel.getHeight(), SCALE_SMOOTH);
        imgFinal=new ImageIcon(pic);
       //picTxtFld.setText(fName);
       //request.setImgIcon(imgFinal);
       cropImageJLabel.setIcon(imgFinal);
        
    }//GEN-LAST:event_uploadImageJButtonActionPerformed

    private void postJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postJButtonActionPerformed
        // TODO add your handling code here:
        try{
//        String farmerName  = farmerNamejTextField.getText();
//        if(farmerName.length()==0){
//            JOptionPane.showMessageDialog(null, "Please Enter farmer's Name");
//            return;
//        }
        String cropName = cropNameJTextField.getText();
        if(cropName.length()==0){
            JOptionPane.showMessageDialog(null, "Please Enter Crop's Name");
            return;
        }
        int quantity = Integer.parseInt(qtyTxtField.getText());
        double ratePerKg = Double.parseDouble(ratePerKgTxtF.getText());
        String senderAdress1 = senderAddL1TextField.getText();
        if(senderAdress1.length()==0){
            JOptionPane.showMessageDialog(null, "Please Enter Line 1");
            return;
        }
        String senderAdress2 = senderAddLine2TextField.getText();
        if(senderAdress2.length()==0){
            JOptionPane.showMessageDialog(null, "Please Enter Line 2");
            return;
        }
        int senderZipcode = Integer.parseInt(senderZipcodeJTextField.getText());
        long contactNo = Long.parseLong(senderContactJTextField.getText());
        String cropDesc = cropDescJTextArea.getText();
        
        MarketWorkRequest marketWorkRequest = new MarketWorkRequest();
        marketWorkRequest.setSender(userAccount);
        marketWorkRequest.setCropName(cropName);
        marketWorkRequest.setQuantity(quantity);
        marketWorkRequest.setRatePerKg(ratePerKg);
        marketWorkRequest.setSenderAddressLine1(senderAdress1);
        marketWorkRequest.setSenderAddressLine2(senderAdress2);
        marketWorkRequest.setSenderZipcode(senderZipcode);
        marketWorkRequest.setSenderContactInfo(contactNo);
        marketWorkRequest.setCropDesc(cropDesc);
        marketWorkRequest.setCropImage(imgFinal);
        
        Organization org = null;
        for(Network network : business.getNetworkList())
        {
            for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList())
            {    
               for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList())
               {
                    if (organization instanceof MarketingOrganization)
                    {
                        org = organization;
                        org.getMarketWorkQueue().getMarkerWorkRequestList().add(marketWorkRequest);
                            //break;
                        //Adding in all markets of all networks    
                    }
                } 
            }
        }
        
        if (org!=null)
        {
            //org.getMarketWorkQueue().getMarkerWorkRequestList().add(marketWorkRequest);
            userAccount.getMarketWorkQueue().getMarkerWorkRequestList().add(marketWorkRequest);
        }
        populateMarketSellTable();
        JOptionPane.showMessageDialog(null, "Successfully Posted");
        farmerNamejTextField.setText("");
        cropNameJTextField.setText("");
        senderAddL1TextField.setText("");
        senderAddLine2TextField.setText("");
        senderZipcodeJTextField.setText("");
        senderContactJTextField.setText("");
        qtyTxtField.setText("");
        ratePerKgTxtF.setText("");
        cropDescJTextArea.setText("");
        cropImageJLabel.setIcon(null);
        
        }
        
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Please input valid entries");
        }
        
    }//GEN-LAST:event_postJButtonActionPerformed

    private void viewJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = sellCropJTable.getSelectedRow();
       
       if (selectedRow < 0){
           JOptionPane.showMessageDialog(null, "Please select a row");
           return;
       }
       try{
       MarketWorkRequest request = (MarketWorkRequest)sellCropJTable.getValueAt(selectedRow, 0);
       
       ViewOrderDetails viewOrderDetails = new ViewOrderDetails(userProcessContainer, userAccount, request);
       userProcessContainer.add("viewcropdetails", viewOrderDetails);
       CardLayout layout = (CardLayout) userProcessContainer.getLayout();
       layout.next(userProcessContainer);
       }
       catch(Exception e){
           JOptionPane.showMessageDialog(null, "No Vendor Has Responded Yet");
       }
        
    }//GEN-LAST:event_viewJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JTextArea cropDescJTextArea;
    private javax.swing.JLabel cropImageJLabel;
    private javax.swing.JTextField cropNameJTextField;
    private javax.swing.JTextField farmerNamejTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton postJButton;
    private javax.swing.JTextField qtyTxtField;
    private javax.swing.JTextField ratePerKgTxtF;
    private javax.swing.JTable sellCropJTable;
    private javax.swing.JTextField senderAddL1TextField;
    private javax.swing.JTextField senderAddLine2TextField;
    private javax.swing.JTextField senderContactJTextField;
    private javax.swing.JTextField senderZipcodeJTextField;
    private javax.swing.JButton uploadImageJButton;
    private javax.swing.JButton viewJButton;
    // End of variables declaration//GEN-END:variables
}
