/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Farmer.Farmer;
import Business.Network.Network;
import Business.Organization.FarmerOrganization;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.Role.FarmerRole;
import Business.UserAccount.UserAccount;
import UserInterface.SystemAdminRole.ManageEnterpriseAdminJPanel;
import UserInterface.SystemAdminRole.ManageNetworkJPanel;
import java.awt.CardLayout;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;



/**
 *
 * @author Lenovo
 */
public class SignUpJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SignUpJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem system;
    private BufferedImage image1;
    private Image image2;
    
    
    public SignUpJPanel(JPanel userProcessContainer, EcoSystem system){
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        //imageLabel.setSize(1200,800);
        
        populateNetworkComboBox();
        backgroundImage("/resources/imgs/HP2.jpg");
    }
    
    private void backgroundImage(String str){
        
        try {
            BufferedImage image1 = ImageIO.read(SignUpJPanel.class.getResource(str));
            image2 = image1.getScaledInstance(1200,800,Image.SCALE_SMOOTH);
        } catch (IOException ex) {
            Logger.getLogger(SignUpJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    public void paintComponent(Graphics g) {
    super.paintComponent(g);

    // Draw the background image.
    g.drawImage(image2, 0, 0, this);
  }
    
    
    
    private void populateNetworkComboBox(){
        networkJComboBox.removeAllItems();
        
        for (Network network : system.getNetworkList()){
            networkJComboBox.addItem(network);
        }
    }
    
    private void populateEnterpriseComboBox(Network network){
        enterpriseJComboBox.removeAllItems();
        
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
            if((enterprise.getEnterpriseType().getValue().equals("Agriculture")))
            {
                enterpriseJComboBox.addItem(enterprise);
            }
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        farmerNameTextField = new javax.swing.JTextField();
        userNameTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        createAccountBtn = new javax.swing.JButton();
        passwordTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        networkJComboBox = new javax.swing.JComboBox();
        enterpriseJComboBox = new javax.swing.JComboBox();
        passwordValidationJLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Please Fill The Details To Create Your Account");
        add(jLabel1);
        jLabel1.setBounds(220, 190, 550, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Name :");
        add(jLabel2);
        jLabel2.setBounds(320, 250, 80, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("User Name:");
        add(jLabel3);
        jLabel3.setBounds(320, 300, 80, 15);

        backBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn);
        backBtn.setBounds(60, 520, 90, 23);
        add(farmerNameTextField);
        farmerNameTextField.setBounds(450, 250, 166, 30);
        add(userNameTextField);
        userNameTextField.setBounds(450, 290, 166, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Password:");
        add(jLabel4);
        jLabel4.setBounds(320, 340, 70, 15);

        createAccountBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        createAccountBtn.setText("Create Account");
        createAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountBtnActionPerformed(evt);
            }
        });
        add(createAccountBtn);
        createAccountBtn.setBounds(470, 520, 140, 23);
        add(passwordTextField);
        passwordTextField.setBounds(450, 340, 166, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Networks:");
        add(jLabel5);
        jLabel5.setBounds(320, 400, 70, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Enterprise:");
        add(jLabel6);
        jLabel6.setBounds(320, 440, 80, 15);

        networkJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        networkJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkJComboBoxActionPerformed(evt);
            }
        });
        add(networkJComboBox);
        networkJComboBox.setBounds(450, 400, 170, 30);

        enterpriseJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        enterpriseJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterpriseJComboBoxActionPerformed(evt);
            }
        });
        add(enterpriseJComboBox);
        enterpriseJComboBox.setBounds(450, 440, 170, 30);
        add(passwordValidationJLabel);
        passwordValidationJLabel.setBounds(630, 340, 358, 28);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imgs/agronomyAdvancement.JPG"))); // NOI18N
        add(jLabel7);
        jLabel7.setBounds(0, 0, 1310, 130);
    }// </editor-fold>//GEN-END:initComponents

    private void createAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountBtnActionPerformed
        //Enterprise enterprise = (Enterprise) enterpriseNameComboBox.getSelectedItem();
        
        String username = userNameTextField.getText();
        String password = passwordTextField.getText();
        String name = farmerNameTextField.getText();
        
        if(userNameTextField.getText().length()==0 || passwordTextField.getText().length()==0 || farmerNameTextField.getText().length()==0){  
        JOptionPane.showMessageDialog(null, "Please Enter all the Fields");
        return;
        }
        
        if(!(Pattern.matches("^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z\\d]{8,}$", password))){
        JOptionPane.showMessageDialog(null, "Please enter a valid password");
        passwordValidationJLabel.setText("Password must be 8 charaters with 1 alphabet & 1 digit");
        return;
        
        }
        
        Enterprise selecedEnterprise = (Enterprise) enterpriseJComboBox.getSelectedItem();

            for(Organization organization : selecedEnterprise.getOrganizationDirectory().getOrganizationList())
            {
                if(organization instanceof FarmerOrganization){
                    Farmer farmer =  organization.getFarmerDirectory().createFarmer(name);
                    UserAccount account = organization.getUserAccountDirectory().createUserAccount(username, password, null,farmer, new FarmerRole());
                    //Farmer farmer =  organization.getFarmerDirectory().createFarmer(name);
                    
                    
                }
            }
        farmerNameTextField.setText("");    
        userNameTextField.setText("");
        passwordTextField.setText("");
        JOptionPane.showMessageDialog(null, "Your account is created Succesffully");
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
        
        
        
       
    }//GEN-LAST:event_createAccountBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void enterpriseJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterpriseJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterpriseJComboBoxActionPerformed

    private void networkJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkJComboBoxActionPerformed
        // TODO add your handling code here:
        Network network = (Network) networkJComboBox.getSelectedItem();
        if (network != null){
            populateEnterpriseComboBox(network);
        }
    }//GEN-LAST:event_networkJComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton createAccountBtn;
    private javax.swing.JComboBox enterpriseJComboBox;
    private javax.swing.JTextField farmerNameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox networkJComboBox;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JLabel passwordValidationJLabel;
    private javax.swing.JTextField userNameTextField;
    // End of variables declaration//GEN-END:variables
}
